on:
  pull_request:
    branches:
    - master

name: Pull Request
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: create artifacts dir to save test logs
      run: mkdir artifacts
    - name: Test with pytest
      run: |
        pytest 2>&1 | tee artifacts/test.log
        result_code=${PIPESTATUS[0]}
        echo "::set-output name=pytest::$(cat artifacts/test.log)"
        exit $result_code
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test_artifacts
        path: artifacts
